### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by ZiWang1105** [autonomousvision/sledge#1]
Dear authors, thanks for your awesome work!! May I kindly ask when are you going to release your code?

**Comment by DanielDauner** [comment]
Hey @ZiWang1105 

Thanks for your kind words and your interest in our project!

We do not have a certain date of when the code will be ready for release. While we're aiming for an earlier date, we've set a firm deadline for ourselves by mid-June. I will leave this issue open and keep you posted for any news!

Best, Daniel

**Comment by Syzygianinfern0** [comment]
@DanielDauner is there any update on the code release? If the code release will take longer, is it possible to release just the new harder scenarios separately in the meantime?

**Comment by DanielDauner** [comment]
Hey @Syzygianinfern0, I will give a brief update on the release. 

For the paper, we implemented autoencoder training with tuplan-garage / nuplan-devkit and the diffusion model with HuggingFace Diffusers. We are currently re-formulating all parts of SLEDGE as a standalone framework (and more up-to-date dependencies). Unfortunately, releasing the longer scenarios might be towards the end of the release. I will consider options to pre-release certain parts.

Thanks for your patience and understanding.

**Comment by zhouyunsong** [comment]
Hi @DanielDauner, thanks for your impressive work. I just wondering is there any update on the code release.

**Comment by DanielDauner** [comment]
We will release a v0.1 soon, which implements the main components, such as autoencoder training, diffusion training, and some basic simulations with visualizations.

I need a few more days.

**Comment by DanielDauner** [comment]
Notify: @ZiWang1105 @Syzygianinfern0 @zhouyunsong

Hey everyone,

We're excited to release SLEDGE v0.1! This version includes code for feature processing, training the autoencoder and diffusion models, and some basic simulations of synthetic scenarios.

This release was a lot of work, and there's more to come—we're still working on releasing checkpoints, metrics, and the full simulation code.  More updates will follow.

If you have any questions, suggestions, or run into issues, please don't hesitate to reach out or open an issue.

Thanks a lot for your interest and patience! Happy sledging 🛷
