### ISSUE TITLE
Why is nuplan data required.

### ISSUE THREAD

**Issue by deo-abhijit** [autonomousvision/sledge#3]
Hi! 
Thanks for sharing the code! 

I am trying to understand the paper. so in the abstract of the paper, it says, 

```
Compared to nuPlan, SLEDGE requires 500× less storage to set up (<4 GB), making it a more accessible
option and helping with democratizing future research in this field.
```

But in the installation, there is a [step](https://github.com/autonomousvision/sledge/blob/main/docs/installation.md#2-download-the-data) to download the nuplan data. Can i use sledge without this data? 

Thanks.

**Comment by deo-abhijit** [comment]
is it  for training the autoencoder?

**Comment by DanielDauner** [comment]
Hi @deo-abhijit

Yes, the complete nuPlan dataset is only required if you want to train the autoencoder from scratch _and_ with input features different from the default. We provide a download of the default autoencoder features with the ~500k samples in `download_cache.sh`.

The <4 GB refers to the SLEDGE simulation with a trained diffusion model and the nuPlan maps. We will make this more clear in the updated docs and are working on the checkpoint release.

Best,
Daniel

**Comment by deo-abhijit** [comment]
Understood! Thanks
