### ISSUE TITLE
Map layers

### ISSUE THREAD

**Issue by hamid54** [autonomousvision/sledge#7]
Hi,

As for input/output channels, Sledge has distinct channels for lanes (baseline, green, and red). However, there is no information available regarding the roads, which consist of a set of lanes and drivable areas. I am curious whether this aspect is specifically addressed or currently disregarded.

Thank you!
Hamid

**Comment by DanielDauner** [comment]
Hi @hamid54 

Thanks for this question!

We do not model the surface polygons and of the maps in SLEDGE. We assume a constant lane width of 3m in the `Lane & Agent` simulation (see [here](https://github.com/autonomousvision/sledge/blob/345a0c33e3a7b5e6aae9de37a6ff387ae3ab9402/sledge/simulation/maps/sledge_map/sledge_map_graph.py#L53)), which is similarly done in [DriveSceneGen](https://github.com/SS47816/DriveSceneGen). In the `Lane -> Agent` mode, we just used the nuPlan map.

I hope that helps!
Daniel
